## Kaggle Faker News Classifier Using LSTM- Deep LEarning| Natural Language Processing

Dataset: http://www.kaggle.com/c/fake-news/data#

In [20]:
import pandas as pd

In [21]:
df= pd.read_csv('fake-news/train_fake-news.csv')

In [22]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [23]:
## Drop nan values
df=df.dropna()

In [24]:
# Get the Independent Features
X=df.drop('label', axis=1)

In [25]:
# Get the dependent Features
y=df['label']

In [26]:
X.shape

(18285, 4)

In [27]:
y.shape

(18285,)

In [28]:
import tensorflow as tf

In [29]:
tf.__version__

'2.3.0'

In [30]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout

In [31]:
# Vocabulary size
voc_size=5000

# OneHot Reprasentation

In [32]:
messages=X.copy()

In [33]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [34]:
messages.reset_index(inplace=True)

In [35]:
messages

index     id                                              title  \
0          0      0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2      2                  Why the Truth Might Get You Fired   
3          3      3  15 Civilians Killed In Single US Airstrike Hav...   
4          4      4  Iranian woman jailed for fictional unpublished...   
...      ...    ...                                                ...   
18280  20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
18281  20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
18282  20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
18283  20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
18284  20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
18280                              Jerome Hudson   
18281                           Benjamin Hoffman   
18282  Michael J. de la Merced and Rachel Abrams   
18283                                Alex Ansary   
18284                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
18280  Rapper T. I. unloaded on black celebrities who...  
18281  When the Green Bay Packers lost to the Washing...  
18282  The Macy’s of today grew from the union of sev...  
18283  NATO, Russia To Hold Parallel Exercises In Bal...  
18284    David Swanson is an author, activist, journa...  

[18285 rows x 5 columns]

In [36]:
import nltk
import re
from nltk.corpus import stopwords

In [37]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\abdul\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

## Data set Preprocessing

In [38]:
from nltk.stem.porter import PorterStemmer # Stemming

In [39]:
ps= PorterStemmer()
corpus=[]

for i in range(0, len(messages)):
    #print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words("english")]
    review = ' '.join(review)
    corpus.append(review)

In [40]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

## Onehot Reprasentation¶

In [41]:
onehot_repr=[one_hot(words, voc_size) for words in corpus]
onehot_repr

[[505, 3049, 3971, 4390, 2864, 2940, 1131, 1106, 217, 3225],
 [2457, 3354, 4802, 227, 963, 3920, 1872],
 [3146, 4767, 1281, 464],
 [4949, 798, 2924, 357, 3647, 3425],
 [2911, 963, 2255, 640, 3942, 4037, 963, 3538, 95, 541],
 [193,
  4157,
  1595,
  2483,
  839,
  1528,
  845,
  272,
  1901,
  4204,
  1213,
  3984,
  380,
  2065,
  1872],
 [1382, 3149, 4613, 3857, 527, 4720, 2537, 4683, 3538, 2606, 2607],
 [3036, 4689, 2257, 570, 1989, 4159, 1528, 356, 3538, 2606, 2607],
 [3661, 633, 3244, 1951, 3256, 2846, 4321, 666, 1528, 248],
 [4291, 828, 2376, 2303, 560, 2298, 3324, 1881],
 [1190, 4638, 2794, 3237, 3233, 2533, 3908, 3421, 3037, 2118, 225],
 [357, 1631, 2864, 2846, 1528, 1989],
 [4737, 4351, 3185, 1683, 4882, 4021, 4481, 1190, 782],
 [4681, 937, 3870, 4260, 2632, 3049, 3687, 3538, 2606, 2607],
 [920, 2133, 4460, 320, 4970, 3538, 2606, 2607],
 [3882, 1113, 3863, 2933, 2153, 4132, 4035, 3674, 1066, 2838],
 [1803, 118, 3354],
 [3188, 2170, 4257, 3621, 1528, 1319, 938, 1872],
 [4845, 67

## Word Embedding Reprasentation

In [42]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr, padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 1106  217 3225]
 [   0    0    0 ...  963 3920 1872]
 [   0    0    0 ... 4767 1281  464]
 ...
 [   0    0    0 ... 3538 2606 2607]
 [   0    0    0 ... 4396 3784 2623]
 [   0    0    0 ... 1304 2737 4271]]


## Creating Model

In [67]:
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size, embedding_vector_features,input_length=sent_length))
#model.add(Dropout(0.3))
model.add(LSTM(100))
#model.add(Dropout(0.3))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam', metrics=['accuracy'] )
print(model.summary())

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, 20, 40)            200000    
_________________________________________________________________
lstm_4 (LSTM)                (None, 100)               56400     
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [68]:
import numpy as np

In [69]:
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [70]:
X_final.shape

(18285, 20)

In [71]:
y_final.shape

(18285,)

In [72]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X_final,y_final, test_size=0.33, random_state=42)

## Model Training

In [73]:
## Finally Training
model.fit(X_train, y_train, validation_data=(X_test,y_test), epochs=10, batch_size=64)

Epoch 1/10
192/192 [==============================] - 4s 19ms/step - loss: 0.3393 - accuracy: 0.8331 - val_loss: 0.1942 - val_accuracy: 0.9200
Epoch 2/10
192/192 [==============================] - 3s 17ms/step - loss: 0.1376 - accuracy: 0.9469 - val_loss: 0.2007 - val_accuracy: 0.9148
Epoch 3/10
192/192 [==============================] - 4s 19ms/step - loss: 0.0913 - accuracy: 0.9674 - val_loss: 0.2156 - val_accuracy: 0.9220
Epoch 4/10
192/192 [==============================] - 4s 19ms/step - loss: 0.0602 - accuracy: 0.9798 - val_loss: 0.2773 - val_accuracy: 0.9180
Epoch 5/10
192/192 [==============================] - 3s 18ms/step - loss: 0.0361 - accuracy: 0.9887 - val_loss: 0.3284 - val_accuracy: 0.9147
Epoch 6/10
192/192 [==============================] - 3s 16ms/step - loss: 0.0210 - accuracy: 0.9934 - val_loss: 0.5139 - val_accuracy: 0.9117
Epoch 7/10
192/192 [==============================] - 3s 16ms/step - loss: 0.0136 - accuracy: 0.9968 - val_loss: 0.4560 - val_accuracy: 0.9112

## Performance Matrix and Accuracy 

In [74]:
y_pred=model.predict_classes(X_test)

In [75]:
from sklearn.metrics import confusion_matrix

In [76]:
confusion_matrix(y_test, y_pred)

array([[3158,  261],
       [ 277, 2339]], dtype=int64)

In [77]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.9108533554266777

## Adding Dropout

In [78]:
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size, embedding_vector_features,input_length=sent_length))
#model.add(Dropout(0.3))
model.add(LSTM(100))
#model.add(Dropout(0.3))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam', metrics=['accuracy'] )
print(model.summary())

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_5 (Embedding)      (None, 20, 40)            200000    
_________________________________________________________________
lstm_5 (LSTM)                (None, 100)               56400     
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None
